# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'GPUImage', '~> 0.1.7'
   pod 'GPUImageBeautifyFilter', '~> 1.0.0'

  # Pods for VideoTool

end
